workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: "3.22.3"  # Replace with your Flutter version
      xcode: "14.2"      # Replace with your Xcode version
    scripts:
      - name: Clean project
        script: flutter clean
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod install --repo-update
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
