workflows:
  ios-workflow:
    name: iOS build
    environment:
      flutter: 3.24
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter clean 
          flutter pub get
          cd ios
          pod install
      - name: Build iOS app
        script: flutter build ios --release  --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
