// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt5fgNrH2dl3flt8W2vnvb_sEPNMRqGZs',
    appId: '1:1024351045261:web:9f536a39ecda56123f84c4',
    messagingSenderId: '1024351045261',
    projectId: 'cinso-global',
    authDomain: 'cinso-global.firebaseapp.com',
    databaseURL: 'https://cinso-global-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cinso-global.appspot.com',
    measurementId: 'G-WGDNCBX0D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCfy1L8pDM_twxryF6nj7NZOJNZZEnSlY',
    appId: '1:1024351045261:android:71eb3731c604d8ed3f84c4',
    messagingSenderId: '1024351045261',
    projectId: 'cinso-global',
    databaseURL: 'https://cinso-global-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cinso-global.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9CQqOQyuRpM0xjRK8jeYy4jhPQpmOkdU',
    appId: '1:1024351045261:ios:2b67e317b1203ff23f84c4',
    messagingSenderId: '1024351045261',
    projectId: 'cinso-global',
    databaseURL: 'https://cinso-global-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cinso-global.appspot.com',
    androidClientId: '1024351045261-pii5mc3d9g16net7s4lrrkpi4bgi9fai.apps.googleusercontent.com',
    iosClientId: '1024351045261-139s0t0mfkscuaat9gkmqv0hr4tgm183.apps.googleusercontent.com',
    iosBundleId: 'com.ihsuraa.cinso.cinsoBackup',
  );

}